//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NorthwindContext : DbContext
    {
        public NorthwindContext()
            : base("name=NorthwindContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatalogoPermiso> CatalogoPermisos { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Order_Detail> Order_Details { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Permiso> Permisos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Shipper> Shippers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<VwCategoriasConProducto> VwCategoriasConProductos { get; set; }
        public virtual DbSet<VwClientesProveedore> VwClientesProveedores { get; set; }
        public virtual DbSet<VwProductosPorEncimaDelPrecioPromedio> VwProductosPorEncimaDelPrecioPromedios { get; set; }
    
        public virtual ObjectResult<SpCategoriaBuscar_Result> SpCategoriaBuscar(Nullable<int> idIni, Nullable<int> idFin, string categoryName)
        {
            var idIniParameter = idIni.HasValue ?
                new ObjectParameter("IdIni", idIni) :
                new ObjectParameter("IdIni", typeof(int));
    
            var idFinParameter = idFin.HasValue ?
                new ObjectParameter("IdFin", idFin) :
                new ObjectParameter("IdFin", typeof(int));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpCategoriaBuscar_Result>("SpCategoriaBuscar", idIniParameter, idFinParameter, categoryNameParameter);
        }
    
        public virtual ObjectResult<SpCategoriaObtener_Result> SpCategoriaObtener(Nullable<bool> top100)
        {
            var top100Parameter = top100.HasValue ?
                new ObjectParameter("top100", top100) :
                new ObjectParameter("top100", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpCategoriaObtener_Result>("SpCategoriaObtener", top100Parameter);
        }
    
        public virtual int SpCategoriaEliminar(Nullable<int> categoryID, byte[] rowVersion)
        {
            var categoryIDParameter = categoryID.HasValue ?
                new ObjectParameter("CategoryID", categoryID) :
                new ObjectParameter("CategoryID", typeof(int));
    
            var rowVersionParameter = rowVersion != null ?
                new ObjectParameter("RowVersion", rowVersion) :
                new ObjectParameter("RowVersion", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpCategoriaEliminar", categoryIDParameter, rowVersionParameter);
        }
    
        public virtual int SpCategoriaInsertar(string categoryName, string description, byte[] picture, ObjectParameter categoryID)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("CategoryName", categoryName) :
                new ObjectParameter("CategoryName", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var pictureParameter = picture != null ?
                new ObjectParameter("Picture", picture) :
                new ObjectParameter("Picture", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpCategoriaInsertar", categoryNameParameter, descriptionParameter, pictureParameter, categoryID);
        }
    }
}
