//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public int UsuarioId { get; set; }
        public int PermisoId { get; set; }
        public Nullable<System.DateTime> FechaDeCreacion { get; set; }
    
        public virtual CatalogoPermiso CatalogoPermiso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
