//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwProductosPorEncimaDelPrecioPromedio
    {
        public Nullable<long> Fila { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioPromedio { get; set; }
        public Nullable<decimal> Diferencia { get; set; }
        public Nullable<decimal> PorcentajeSobrePromedio { get; set; }
        public string Categoria { get; set; }
        public string Proveedor { get; set; }
    }
}
